using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using Occult.Properties;

namespace Occult.Star_Catalogues
{
	public class WDS_Interferometer_Display : Form
	{
		internal double CentreRA;

		internal double CentreDec;

		private const double Radian = 180.0 / Math.PI;

		internal static string VariableID = "";

		private IContainer components;

		internal ListBox lstIF;

		private MenuStrip menuStrip1;

		private ToolStripMenuItem copyToolStripMenuItem;

		private ToolStripMenuItem exitToolStripMenuItem;

		private ToolStripMenuItem copyToolStripMenuItem1;

		private ToolStripMenuItem printToolStripMenuItem;

		private ToolStripMenuItem helpToolStripMenuItem;

		private Button cmdRead;

		private TextBox txtRAh;

		private TextBox txtRAm;

		private TextBox txtDecD;

		private TextBox txtDecM;

		private Label label1;

		private Label label2;

		private Label label3;

		private Label label4;

		private Label label5;

		private Label label6;

		private Button cmdGoogleSky;

		private Label label7;

		internal Button cmdAAVSO;

		internal Button cmdDisplayOrbit;

		public WDS_Interferometer_Display()
		{
			InitializeComponent();
		}

		private void exitToolStripMenuItem_Click(object sender, EventArgs e)
		{
			((Form)this).Close();
			((Component)this).Dispose();
		}

		private void menuStrip1_Resize(object sender, EventArgs e)
		{
			if (!((((Control)this).get_Width() < 200) | (((Control)this).get_Height() < 80)))
			{
				((Control)lstIF).set_Width(((Control)this).get_Width() - 40);
				((Control)lstIF).set_Height(((Control)this).get_Height() - 100);
			}
		}

		private void copyToolStripMenuItem1_Click(object sender, EventArgs e)
		{
			string text = "";
			for (int i = 0; i < lstIF.get_Items().get_Count(); i++)
			{
				text = text + lstIF.get_Items().get_Item(i).ToString() + "\r\n";
			}
			Clipboard.SetText(text);
		}

		private void printToolStripMenuItem_Click(object sender, EventArgs e)
		{
			string text = "";
			for (int i = 0; i < lstIF.get_Items().get_Count(); i++)
			{
				text = text + lstIF.get_Items().get_Item(i).ToString() + "\r\n";
			}
			Output.PrintText_Landscape(text, 8);
		}

		private void helpToolStripMenuItem_Click(object sender, EventArgs e)
		{
			Help.ShowHelp((Control)(object)this, Utilities.AppPath + "\\Occult.chm", (HelpNavigator)(-2147483642), (object)"WDS Format");
		}

		private void cmdRead_Click(object sender, EventArgs e)
		{
			if (!int.TryParse(((Control)txtRAh).get_Text(), out var result))
			{
				result = 0;
			}
			if (!double.TryParse(((Control)txtRAm).get_Text(), out var result2))
			{
				result2 = 0.0;
			}
			if (!int.TryParse(((Control)txtDecD).get_Text().Replace("-", ""), out var result3))
			{
				result3 = 0;
			}
			if (!double.TryParse(((Control)txtDecM).get_Text(), out var result4))
			{
				result4 = 0.0;
			}
			double num = (double)result + result2 / 60.0;
			double num2 = (double)result3 + result4 / 60.0;
			if (((Control)txtDecD).get_Text().Contains("-"))
			{
				num2 = 0.0 - num2;
			}
			VariableID = Interferometric_Plus_WDS.Find_WDS_IF_Matches(num, num2, HighPrecision: false, ShowResults: true);
			CentreRA = num * 15.0;
			CentreDec = num2;
			((Control)cmdAAVSO).set_Enabled(VariableID != "");
			((Control)cmdAAVSO).set_Text("Get light curve : " + VariableID);
		}

		private void txtRAh_Enter(object sender, EventArgs e)
		{
			((TextBoxBase)txtRAh).SelectAll();
		}

		private void txtRAh_MouseEnter(object sender, EventArgs e)
		{
			((TextBoxBase)txtRAh).SelectAll();
		}

		private void txtRAm_Enter(object sender, EventArgs e)
		{
			((TextBoxBase)txtRAm).SelectAll();
		}

		private void txtRAm_MouseEnter(object sender, EventArgs e)
		{
			((TextBoxBase)txtRAm).SelectAll();
		}

		private void txtDecD_Enter(object sender, EventArgs e)
		{
			((TextBoxBase)txtDecD).SelectAll();
		}

		private void txtDecD_MouseEnter(object sender, EventArgs e)
		{
			((TextBoxBase)txtDecD).SelectAll();
		}

		private void txtDecM_Enter(object sender, EventArgs e)
		{
			((TextBoxBase)txtDecM).SelectAll();
		}

		private void txtDecM_MouseEnter(object sender, EventArgs e)
		{
			((TextBoxBase)txtDecM).SelectAll();
		}

		private void cmdGoogleSky_Click(object sender, EventArgs e)
		{
			int width_in_arcMins = 5;
			GoogleEarth.CreateGoogleSkyKMLFile(CentreRA, CentreDec, width_in_arcMins, Utilities.AppPath + "\\AutoGenerated Asteroids\\ViewGoogleSky.KML");
		}

		private void WDS_Interferometer_Display_Load(object sender, EventArgs e)
		{
			if (((Control)this).get_Top() < -30000)
			{
				((Control)this).set_Top(0);
			}
			if ((double)((Control)this).get_Left() + (double)((Control)this).get_Width() / 1.2 < (double)Screen.GetWorkingArea((Control)(object)this).Left)
			{
				((Control)this).set_Left(Screen.GetWorkingArea((Control)(object)this).Left);
			}
			((Control)this).set_Text(((Control)this).get_Text() + " : Occult v." + Utilities.OccultVersion_Short);
		}

		private void cmdAAVSO_Click(object sender, EventArgs e)
		{
			//IL_0011: Unknown result type (might be due to invalid IL or missing references)
			if (!Utilities.InternetIsAvailable())
			{
				MessageBox.Show("This functionality requires internet access. You are not connected to the internet", "No internet");
				return;
			}
			Interferometric_Plus_WDS.ShowLightCurve(VariableID);
			Interferometric_Plus_WDS.AAVSO.GetLightCurve();
		}

		private void WDS_Interferometer_Display_Resize(object sender, EventArgs e)
		{
			((Control)lstIF).set_Width(((Control)this).get_Width() - 29);
			((Control)lstIF).set_Height(((Control)this).get_Height() - 103);
		}

		private void cmdDisplayOrbit_Click(object sender, EventArgs e)
		{
			Interferometric_Plus_WDS.ShowDisplayOrbit();
			Interferometric_Plus_WDS.DisplayOrbit.InitialDisplay();
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null)
			{
				components.Dispose();
			}
			((Form)this).Dispose(disposing);
		}

		private void InitializeComponent()
		{
			//IL_0011: Unknown result type (might be due to invalid IL or missing references)
			//IL_001b: Expected O, but got Unknown
			//IL_001c: Unknown result type (might be due to invalid IL or missing references)
			//IL_0026: Expected O, but got Unknown
			//IL_0027: Unknown result type (might be due to invalid IL or missing references)
			//IL_0031: Expected O, but got Unknown
			//IL_0032: Unknown result type (might be due to invalid IL or missing references)
			//IL_003c: Expected O, but got Unknown
			//IL_003d: Unknown result type (might be due to invalid IL or missing references)
			//IL_0047: Expected O, but got Unknown
			//IL_0048: Unknown result type (might be due to invalid IL or missing references)
			//IL_0052: Expected O, but got Unknown
			//IL_0053: Unknown result type (might be due to invalid IL or missing references)
			//IL_005d: Expected O, but got Unknown
			//IL_005e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0068: Expected O, but got Unknown
			//IL_0069: Unknown result type (might be due to invalid IL or missing references)
			//IL_0073: Expected O, but got Unknown
			//IL_0074: Unknown result type (might be due to invalid IL or missing references)
			//IL_007e: Expected O, but got Unknown
			//IL_007f: Unknown result type (might be due to invalid IL or missing references)
			//IL_0089: Expected O, but got Unknown
			//IL_008a: Unknown result type (might be due to invalid IL or missing references)
			//IL_0094: Expected O, but got Unknown
			//IL_0095: Unknown result type (might be due to invalid IL or missing references)
			//IL_009f: Expected O, but got Unknown
			//IL_00a0: Unknown result type (might be due to invalid IL or missing references)
			//IL_00aa: Expected O, but got Unknown
			//IL_00ab: Unknown result type (might be due to invalid IL or missing references)
			//IL_00b5: Expected O, but got Unknown
			//IL_00b6: Unknown result type (might be due to invalid IL or missing references)
			//IL_00c0: Expected O, but got Unknown
			//IL_00c1: Unknown result type (might be due to invalid IL or missing references)
			//IL_00cb: Expected O, but got Unknown
			//IL_00cc: Unknown result type (might be due to invalid IL or missing references)
			//IL_00d6: Expected O, but got Unknown
			//IL_00d7: Unknown result type (might be due to invalid IL or missing references)
			//IL_00e1: Expected O, but got Unknown
			//IL_00e2: Unknown result type (might be due to invalid IL or missing references)
			//IL_00ec: Expected O, but got Unknown
			//IL_00ed: Unknown result type (might be due to invalid IL or missing references)
			//IL_00f7: Expected O, but got Unknown
			//IL_00f8: Unknown result type (might be due to invalid IL or missing references)
			//IL_0102: Expected O, but got Unknown
			//IL_0ced: Unknown result type (might be due to invalid IL or missing references)
			//IL_0cf7: Expected O, but got Unknown
			ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(WDS_Interferometer_Display));
			lstIF = new ListBox();
			menuStrip1 = new MenuStrip();
			copyToolStripMenuItem = new ToolStripMenuItem();
			copyToolStripMenuItem1 = new ToolStripMenuItem();
			printToolStripMenuItem = new ToolStripMenuItem();
			helpToolStripMenuItem = new ToolStripMenuItem();
			exitToolStripMenuItem = new ToolStripMenuItem();
			cmdRead = new Button();
			txtRAh = new TextBox();
			txtRAm = new TextBox();
			txtDecD = new TextBox();
			txtDecM = new TextBox();
			label1 = new Label();
			label2 = new Label();
			label3 = new Label();
			label4 = new Label();
			label5 = new Label();
			label6 = new Label();
			label7 = new Label();
			cmdDisplayOrbit = new Button();
			cmdAAVSO = new Button();
			cmdGoogleSky = new Button();
			((Control)menuStrip1).SuspendLayout();
			((Control)this).SuspendLayout();
			((Control)lstIF).set_Font(new Font("Courier New", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0));
			((ListControl)lstIF).set_FormattingEnabled(true);
			lstIF.set_HorizontalExtent(950);
			lstIF.set_HorizontalScrollbar(true);
			lstIF.set_ItemHeight(14);
			((Control)lstIF).set_Location(new Point(7, 55));
			((Control)lstIF).set_Name("lstIF");
			((Control)lstIF).set_Size(new Size(855, 312));
			((Control)lstIF).set_TabIndex(0);
			((ToolStrip)menuStrip1).get_Items().AddRange((ToolStripItem[])(object)new ToolStripItem[3]
			{
				(ToolStripItem)copyToolStripMenuItem,
				(ToolStripItem)helpToolStripMenuItem,
				(ToolStripItem)exitToolStripMenuItem
			});
			((Control)menuStrip1).set_Location(new Point(0, 0));
			((Control)menuStrip1).set_Name("menuStrip1");
			((Control)menuStrip1).set_Size(new Size(868, 24));
			((Control)menuStrip1).set_TabIndex(1);
			((Control)menuStrip1).set_Text("menuStrip1");
			((Control)menuStrip1).add_Resize((EventHandler)menuStrip1_Resize);
			((ToolStripDropDownItem)copyToolStripMenuItem).get_DropDownItems().AddRange((ToolStripItem[])(object)new ToolStripItem[2]
			{
				(ToolStripItem)copyToolStripMenuItem1,
				(ToolStripItem)printToolStripMenuItem
			});
			((ToolStripItem)copyToolStripMenuItem).set_Name("copyToolStripMenuItem");
			((ToolStripItem)copyToolStripMenuItem).set_Size(new Size(90, 20));
			((ToolStripItem)copyToolStripMenuItem).set_Text("with List....     ");
			((ToolStripItem)copyToolStripMenuItem1).set_Image((Image)Resources.Copy);
			((ToolStripItem)copyToolStripMenuItem1).set_ImageTransparentColor(Color.Fuchsia);
			((ToolStripItem)copyToolStripMenuItem1).set_Name("copyToolStripMenuItem1");
			((ToolStripItem)copyToolStripMenuItem1).set_Size(new Size(102, 22));
			((ToolStripItem)copyToolStripMenuItem1).set_Text("Copy");
			((ToolStripItem)copyToolStripMenuItem1).add_Click((EventHandler)copyToolStripMenuItem1_Click);
			((ToolStripItem)printToolStripMenuItem).set_Image((Image)Resources.Print);
			((ToolStripItem)printToolStripMenuItem).set_ImageTransparentColor(Color.Fuchsia);
			((ToolStripItem)printToolStripMenuItem).set_Name("printToolStripMenuItem");
			((ToolStripItem)printToolStripMenuItem).set_Size(new Size(102, 22));
			((ToolStripItem)printToolStripMenuItem).set_Text("Print");
			((ToolStripItem)printToolStripMenuItem).add_Click((EventHandler)printToolStripMenuItem_Click);
			((ToolStripItem)helpToolStripMenuItem).set_Image((Image)Resources.help);
			((ToolStripItem)helpToolStripMenuItem).set_Name("helpToolStripMenuItem");
			((ToolStripItem)helpToolStripMenuItem).set_Size(new Size(75, 20));
			((ToolStripItem)helpToolStripMenuItem).set_Text("Help     ");
			((ToolStripItem)helpToolStripMenuItem).add_Click((EventHandler)helpToolStripMenuItem_Click);
			((ToolStripItem)exitToolStripMenuItem).set_Image((Image)Resources.error);
			((ToolStripItem)exitToolStripMenuItem).set_Name("exitToolStripMenuItem");
			((ToolStripItem)exitToolStripMenuItem).set_Size(new Size(72, 20));
			((ToolStripItem)exitToolStripMenuItem).set_Text("Exit      ");
			((ToolStripItem)exitToolStripMenuItem).add_Click((EventHandler)exitToolStripMenuItem_Click);
			((Control)cmdRead).set_Anchor((AnchorStyles)1);
			((Control)cmdRead).set_Location(new Point(54, 27));
			((Control)cmdRead).set_Name("cmdRead");
			((Control)cmdRead).set_Size(new Size(73, 25));
			((Control)cmdRead).set_TabIndex(2);
			((Control)cmdRead).set_Text("Search for :");
			((ButtonBase)cmdRead).set_UseVisualStyleBackColor(true);
			((Control)cmdRead).add_Click((EventHandler)cmdRead_Click);
			((Control)txtRAh).set_Anchor((AnchorStyles)1);
			((Control)txtRAh).set_Location(new Point(170, 32));
			((Control)txtRAh).set_Name("txtRAh");
			((Control)txtRAh).set_Size(new Size(24, 20));
			((Control)txtRAh).set_TabIndex(3);
			((Control)txtRAh).add_Enter((EventHandler)txtRAh_Enter);
			((Control)txtRAh).add_MouseEnter((EventHandler)txtRAh_MouseEnter);
			((Control)txtRAm).set_Anchor((AnchorStyles)1);
			((Control)txtRAm).set_Location(new Point(212, 32));
			((Control)txtRAm).set_Name("txtRAm");
			((Control)txtRAm).set_Size(new Size(31, 20));
			((Control)txtRAm).set_TabIndex(4);
			((Control)txtRAm).add_Enter((EventHandler)txtRAm_Enter);
			((Control)txtRAm).add_MouseEnter((EventHandler)txtRAm_MouseEnter);
			((Control)txtDecD).set_Anchor((AnchorStyles)1);
			((Control)txtDecD).set_Location(new Point(295, 32));
			((Control)txtDecD).set_Name("txtDecD");
			((Control)txtDecD).set_Size(new Size(31, 20));
			((Control)txtDecD).set_TabIndex(5);
			((Control)txtDecD).add_Enter((EventHandler)txtDecD_Enter);
			((Control)txtDecD).add_MouseEnter((EventHandler)txtDecD_MouseEnter);
			((Control)txtDecM).set_Anchor((AnchorStyles)1);
			((Control)txtDecM).set_Location(new Point(332, 32));
			((Control)txtDecM).set_Name("txtDecM");
			((Control)txtDecM).set_Size(new Size(27, 20));
			((Control)txtDecM).set_TabIndex(6);
			((Control)txtDecM).add_Enter((EventHandler)txtDecM_Enter);
			((Control)txtDecM).add_MouseEnter((EventHandler)txtDecM_MouseEnter);
			((Control)label1).set_Anchor((AnchorStyles)1);
			((Control)label1).set_AutoSize(true);
			((Control)label1).set_Location(new Point(215, 18));
			((Control)label1).set_Name("label1");
			((Control)label1).set_Size(new Size(26, 13));
			((Control)label1).set_TabIndex(7);
			((Control)label1).set_Text("m.m");
			((Control)label2).set_Anchor((AnchorStyles)1);
			((Control)label2).set_AutoSize(true);
			((Control)label2).set_Location(new Point(312, 18));
			((Control)label2).set_Name("label2");
			((Control)label2).set_Size(new Size(13, 13));
			((Control)label2).set_TabIndex(8);
			((Control)label2).set_Text("o");
			((Control)label3).set_Anchor((AnchorStyles)1);
			((Control)label3).set_AutoSize(true);
			((Control)label3).set_Location(new Point(344, 23));
			((Control)label3).set_Name("label3");
			((Control)label3).set_Size(new Size(9, 13));
			((Control)label3).set_TabIndex(9);
			((Control)label3).set_Text("'");
			((Control)label4).set_Anchor((AnchorStyles)1);
			((Control)label4).set_AutoSize(true);
			((Control)label4).set_Location(new Point(176, 18));
			((Control)label4).set_Name("label4");
			((Control)label4).set_Size(new Size(13, 13));
			((Control)label4).set_TabIndex(10);
			((Control)label4).set_Text("h");
			((Control)label5).set_Anchor((AnchorStyles)1);
			((Control)label5).set_AutoSize(true);
			((Control)label5).set_Location(new Point(262, 35));
			((Control)label5).set_Name("label5");
			((Control)label5).set_Size(new Size(27, 13));
			((Control)label5).set_TabIndex(11);
			((Control)label5).set_Text("Dec");
			((Control)label6).set_Anchor((AnchorStyles)1);
			((Control)label6).set_AutoSize(true);
			((Control)label6).set_Location(new Point(132, 35));
			((Control)label6).set_Name("label6");
			((Control)label6).set_Size(new Size(28, 13));
			((Control)label6).set_TabIndex(12);
			((Control)label6).set_Text("R.A.");
			((Control)label7).set_AutoSize(true);
			((Control)label7).set_Font(new Font("Microsoft Sans Serif", 6.5f, FontStyle.Regular, GraphicsUnit.Point, 0));
			((Control)label7).set_Location(new Point(283, 7));
			((Control)label7).set_Name("label7");
			((Control)label7).set_Size(new Size(50, 12));
			((Control)label7).set_TabIndex(14);
			((Control)label7).set_Text("GoogleSky");
			((Control)cmdDisplayOrbit).set_Location(new Point(465, 27));
			((Control)cmdDisplayOrbit).set_Name("cmdDisplayOrbit");
			((Control)cmdDisplayOrbit).set_Size(new Size(155, 24));
			((Control)cmdDisplayOrbit).set_TabIndex(16);
			((Control)cmdDisplayOrbit).set_Text("Display orbit");
			((ButtonBase)cmdDisplayOrbit).set_UseVisualStyleBackColor(true);
			((Control)cmdDisplayOrbit).add_Click((EventHandler)cmdDisplayOrbit_Click);
			((ButtonBase)cmdAAVSO).set_Image((Image)Resources.GRAPH01);
			((ButtonBase)cmdAAVSO).set_ImageAlign(ContentAlignment.MiddleLeft);
			((Control)cmdAAVSO).set_Location(new Point(682, 27));
			((Control)cmdAAVSO).set_Name("cmdAAVSO");
			((Control)cmdAAVSO).set_Size(new Size(155, 24));
			((Control)cmdAAVSO).set_TabIndex(15);
			((Control)cmdAAVSO).set_Text("Get light curve of variable");
			((ButtonBase)cmdAAVSO).set_TextAlign(ContentAlignment.MiddleRight);
			((ButtonBase)cmdAAVSO).set_UseVisualStyleBackColor(true);
			((Control)cmdAAVSO).add_Click((EventHandler)cmdAAVSO_Click);
			((Control)cmdGoogleSky).set_BackgroundImage((Image)Resources.sky_mo);
			((Control)cmdGoogleSky).set_BackgroundImageLayout((ImageLayout)2);
			((Control)cmdGoogleSky).set_Location(new Point(256, -1));
			((Control)cmdGoogleSky).set_Name("cmdGoogleSky");
			((Control)cmdGoogleSky).set_Size(new Size(26, 25));
			((Control)cmdGoogleSky).set_TabIndex(13);
			((ButtonBase)cmdGoogleSky).set_UseVisualStyleBackColor(true);
			((Control)cmdGoogleSky).add_Click((EventHandler)cmdGoogleSky_Click);
			((ContainerControl)this).set_AutoScaleDimensions(new SizeF(6f, 13f));
			((ContainerControl)this).set_AutoScaleMode((AutoScaleMode)1);
			((Form)this).set_ClientSize(new Size(868, 376));
			((Control)this).get_Controls().Add((Control)(object)cmdDisplayOrbit);
			((Control)this).get_Controls().Add((Control)(object)cmdAAVSO);
			((Control)this).get_Controls().Add((Control)(object)label7);
			((Control)this).get_Controls().Add((Control)(object)cmdGoogleSky);
			((Control)this).get_Controls().Add((Control)(object)label6);
			((Control)this).get_Controls().Add((Control)(object)label5);
			((Control)this).get_Controls().Add((Control)(object)label4);
			((Control)this).get_Controls().Add((Control)(object)label2);
			((Control)this).get_Controls().Add((Control)(object)label1);
			((Control)this).get_Controls().Add((Control)(object)txtDecM);
			((Control)this).get_Controls().Add((Control)(object)txtDecD);
			((Control)this).get_Controls().Add((Control)(object)txtRAm);
			((Control)this).get_Controls().Add((Control)(object)txtRAh);
			((Control)this).get_Controls().Add((Control)(object)cmdRead);
			((Control)this).get_Controls().Add((Control)(object)lstIF);
			((Control)this).get_Controls().Add((Control)(object)menuStrip1);
			((Control)this).get_Controls().Add((Control)(object)label3);
			((Control)this).get_DataBindings().Add(new Binding("Location", (object)Settings.Default, "LocationStarsWDSIFdisplay", true, (DataSourceUpdateMode)1));
			((Form)this).set_Icon((Icon)componentResourceManager.GetObject("$this.Icon"));
			((Form)this).set_Location(Settings.Default.LocationStarsWDSIFdisplay);
			((Form)this).set_MainMenuStrip(menuStrip1);
			((Control)this).set_MinimumSize(new Size(884, 415));
			((Control)this).set_Name("WDS_Interferometer_Display");
			((Control)this).set_Text("Display of WDS and Interferometric Catalog details");
			((Form)this).add_Load((EventHandler)WDS_Interferometer_Display_Load);
			((Control)this).add_Resize((EventHandler)WDS_Interferometer_Display_Resize);
			((Control)menuStrip1).ResumeLayout(false);
			((Control)menuStrip1).PerformLayout();
			((Control)this).ResumeLayout(false);
			((Control)this).PerformLayout();
		}
	}
}
