using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

namespace Occult.Lunar_Occultations
{
	public class BAAMerge : Form
	{
		private List<BAAPredictions> SiteAll = new List<BAAPredictions>();

		private List<BAAPredictions> Site1 = new List<BAAPredictions>();

		private List<BAAPredictions> Site2 = new List<BAAPredictions>();

		private List<BAAPredictions> Site3 = new List<BAAPredictions>();

		private BAAPredictions P;

		private string[] Sites = new string[3] { "", "", "" };

		private string[] Coords = new string[3] { "", "", "" };

		private int SiteCount;

		private bool CurrentShortLineUsesCA;

		private IContainer components;

		private Label label1;

		private ListBox lstRead;

		private Button cmdRead;

		private Button cmdMerge;

		private Button cmdClear;

		private Button cmdHelp;

		public BAAMerge()
		{
			InitializeComponent();
		}

		private void cmdRead_Click(object sender, EventArgs e)
		{
			//IL_0006: Unknown result type (might be due to invalid IL or missing references)
			//IL_000c: Expected O, but got Unknown
			//IL_002d: Unknown result type (might be due to invalid IL or missing references)
			//IL_0033: Invalid comparison between Unknown and I4
			//IL_0065: Unknown result type (might be due to invalid IL or missing references)
			string text = "";
			OpenFileDialog val = new OpenFileDialog();
			((FileDialog)val).set_InitialDirectory(Utilities.AppPath + "\\AutoGenerated Lunar");
			((FileDialog)val).set_DefaultExt("txt");
			if ((int)((CommonDialog)val).ShowDialog() != 1)
			{
				return;
			}
			Path.GetExtension(((FileDialog)val).get_FileName());
			if (Path.GetExtension(((FileDialog)val).get_FileName()) == ".zip")
			{
				MessageBox.Show("Cannot select a zip file", "zip file selected");
				return;
			}
			lstRead.get_Items().Add((object)((FileDialog)val).get_FileName());
			using (StreamReader streamReader = new StreamReader(((FileDialog)val).get_FileName()))
			{
				text = streamReader.ReadLine();
				Sites[SiteCount] = streamReader.ReadLine()!.Substring(27);
				Coords[SiteCount] = streamReader.ReadLine();
				text = streamReader.ReadLine();
				text = streamReader.ReadLine();
				CurrentShortLineUsesCA = text.Contains("CA");
				text = streamReader.ReadLine();
				do
				{
					P = new BAAPredictions();
					P.ReadLine(streamReader.ReadLine());
					if (SiteCount == 0)
					{
						Site1.Add(P);
					}
					else if (SiteCount == 1)
					{
						Site2.Add(P);
					}
					else if (SiteCount == 2)
					{
						Site3.Add(P);
					}
				}
				while (!streamReader.EndOfStream);
			}
			SiteCount++;
		}

		private void cmdMerge_Click(object sender, EventArgs e)
		{
			//IL_03fc: Unknown result type (might be due to invalid IL or missing references)
			//IL_0402: Expected O, but got Unknown
			//IL_040e: Unknown result type (might be due to invalid IL or missing references)
			//IL_0414: Invalid comparison between Unknown and I4
			SiteAll.Clear();
			for (int i = 0; i < Site1.Count; i++)
			{
				P = new BAAPredictions();
				P.StarEvent = Site1[i].StarEvent;
				P.DateStar = Site1[i].DateStar;
				P.UT1 = Site1[i].UT;
				P.Days = Site1[i].Days;
				SiteAll.Add(P);
			}
			SiteAll.Sort();
			if (SiteCount > 1)
			{
				for (int j = 0; j < Site2.Count; j++)
				{
					bool flag = false;
					for (int k = 0; k < SiteAll.Count; k++)
					{
						if (!(SiteAll[k].Days - Site2[j].Days < -0.4))
						{
							if (SiteAll[k].Days - Site2[j].Days > 0.4)
							{
								break;
							}
							if (SiteAll[k].StarEvent == Site2[j].StarEvent)
							{
								SiteAll[k].UT2 = Site2[j].UT;
								flag = true;
								break;
							}
						}
					}
					if (!flag)
					{
						P = new BAAPredictions();
						P.StarEvent = Site2[j].StarEvent;
						P.DateStar = Site2[j].DateStar;
						P.UT2 = Site2[j].UT;
						P.Days = Site2[j].Days;
						SiteAll.Add(P);
						SiteAll.Sort();
					}
				}
			}
			if (SiteCount > 2)
			{
				for (int l = 0; l < Site3.Count; l++)
				{
					bool flag = false;
					for (int m = 0; m < SiteAll.Count; m++)
					{
						if (!(SiteAll[m].Days - Site3[l].Days < -0.4))
						{
							if (SiteAll[m].Days - Site3[l].Days > 0.4)
							{
								break;
							}
							if (SiteAll[m].StarEvent == Site3[l].StarEvent)
							{
								SiteAll[m].UT3 = Site3[l].UT;
								flag = true;
								break;
							}
						}
					}
					if (!flag)
					{
						P = new BAAPredictions();
						P.StarEvent = Site3[l].StarEvent;
						P.DateStar = Site3[l].DateStar;
						P.UT3 = Site3[l].UT;
						P.Days = Site3[l].Days;
						SiteAll.Add(P);
						SiteAll.Sort();
					}
				}
			}
			SaveFileDialog val = new SaveFileDialog();
			((FileDialog)val).set_DefaultExt("txt");
			if ((int)((CommonDialog)val).ShowDialog() != 1)
			{
				return;
			}
			using StreamWriter streamWriter = new StreamWriter(((FileDialog)val).get_FileName());
			streamWriter.WriteLine("".PadRight(32) + Sites[0].PadRight(25) + Sites[1].PadRight(25) + Sites[2].PadRight(25));
			streamWriter.WriteLine("".PadRight(32) + Coords[0].PadRight(25) + Coords[1].PadRight(25) + Coords[2].PadRight(25));
			if (CurrentShortLineUsesCA)
			{
				streamWriter.WriteLine("   Date     Star  Mag Ph  Ill    U.T.    a    b    CA     U.T.    a    b    CA     U.T.    a    b    CA");
				streamWriter.WriteLine(" y   m  d    No            %    h   m    m    m     o    h   m    m    m     o    h   m    m    m     o");
			}
			else
			{
				streamWriter.WriteLine("   Date     Star  Mag Ph  El     U.T.    a    b    P      U.T.    a    b    P      U.T.    a    b    P");
				streamWriter.WriteLine(" y   m  d    No                 h   m    m    m    o     h   m    m    m    o     h   m    m    m    o");
			}
			for (int n = 0; n < SiteAll.Count; n++)
			{
				if (SiteAll[n].ToString().Trim().Length > 0)
				{
					streamWriter.WriteLine(SiteAll[n].ToString());
				}
			}
		}

		private void cmdClear_Click(object sender, EventArgs e)
		{
			Site1.Clear();
			Site2.Clear();
			Site3.Clear();
			SiteAll.Clear();
			lstRead.get_Items().Clear();
			SiteCount = 0;
			Sites[0] = (Sites[1] = (Sites[2] = ""));
			Coords[0] = (Coords[1] = (Coords[2] = ""));
		}

		private void cmdHelp_Click(object sender, EventArgs e)
		{
			Help.ShowHelp((Control)(object)this, Utilities.AppPath + "\\Occult.chm", (HelpNavigator)(-2147483642), (object)"BAA");
		}

		private void BAAMerge_Load(object sender, EventArgs e)
		{
			((Control)this).set_Text(((Control)this).get_Text() + " : Occult v." + Utilities.OccultVersion_Short);
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null)
			{
				components.Dispose();
			}
			((Form)this).Dispose(disposing);
		}

		private void InitializeComponent()
		{
			//IL_0001: Unknown result type (might be due to invalid IL or missing references)
			//IL_000b: Expected O, but got Unknown
			//IL_000c: Unknown result type (might be due to invalid IL or missing references)
			//IL_0016: Expected O, but got Unknown
			//IL_0017: Unknown result type (might be due to invalid IL or missing references)
			//IL_0021: Expected O, but got Unknown
			//IL_0022: Unknown result type (might be due to invalid IL or missing references)
			//IL_002c: Expected O, but got Unknown
			//IL_002d: Unknown result type (might be due to invalid IL or missing references)
			//IL_0037: Expected O, but got Unknown
			//IL_0038: Unknown result type (might be due to invalid IL or missing references)
			//IL_0042: Expected O, but got Unknown
			label1 = new Label();
			lstRead = new ListBox();
			cmdRead = new Button();
			cmdMerge = new Button();
			cmdClear = new Button();
			cmdHelp = new Button();
			((Control)this).SuspendLayout();
			((Control)label1).set_AutoSize(true);
			((Control)label1).set_Location(new Point(12, 9));
			((Control)label1).set_Name("label1");
			((Control)label1).set_Size(new Size(52, 13));
			((Control)label1).set_TabIndex(7);
			((Control)label1).set_Text("Files read");
			((ListControl)lstRead).set_FormattingEnabled(true);
			((Control)lstRead).set_Location(new Point(12, 26));
			((Control)lstRead).set_Name("lstRead");
			((Control)lstRead).set_Size(new Size(543, 95));
			((Control)lstRead).set_TabIndex(6);
			((Control)cmdRead).set_Location(new Point(12, 132));
			((Control)cmdRead).set_Name("cmdRead");
			((Control)cmdRead).set_Size(new Size(98, 33));
			((Control)cmdRead).set_TabIndex(5);
			((Control)cmdRead).set_Text("Read a file");
			((ButtonBase)cmdRead).set_UseVisualStyleBackColor(true);
			((Control)cmdRead).add_Click((EventHandler)cmdRead_Click);
			((Control)cmdMerge).set_Location(new Point(146, 132));
			((Control)cmdMerge).set_Name("cmdMerge");
			((Control)cmdMerge).set_Size(new Size(96, 33));
			((Control)cmdMerge).set_TabIndex(4);
			((Control)cmdMerge).set_Text("Merge && Save");
			((ButtonBase)cmdMerge).set_UseVisualStyleBackColor(true);
			((Control)cmdMerge).add_Click((EventHandler)cmdMerge_Click);
			((Control)cmdClear).set_Location(new Point(338, 142));
			((Control)cmdClear).set_Name("cmdClear");
			((Control)cmdClear).set_Size(new Size(66, 23));
			((Control)cmdClear).set_TabIndex(8);
			((Control)cmdClear).set_Text("Clear list");
			((ButtonBase)cmdClear).set_UseVisualStyleBackColor(true);
			((Control)cmdClear).add_Click((EventHandler)cmdClear_Click);
			((Control)cmdHelp).set_Location(new Point(480, 142));
			((Control)cmdHelp).set_Name("cmdHelp");
			((Control)cmdHelp).set_Size(new Size(66, 23));
			((Control)cmdHelp).set_TabIndex(9);
			((Control)cmdHelp).set_Text("Help");
			((ButtonBase)cmdHelp).set_UseVisualStyleBackColor(true);
			((Control)cmdHelp).add_Click((EventHandler)cmdHelp_Click);
			((ContainerControl)this).set_AutoScaleDimensions(new SizeF(6f, 13f));
			((ContainerControl)this).set_AutoScaleMode((AutoScaleMode)1);
			((Form)this).set_ClientSize(new Size(563, 172));
			((Control)this).get_Controls().Add((Control)(object)cmdHelp);
			((Control)this).get_Controls().Add((Control)(object)cmdClear);
			((Control)this).get_Controls().Add((Control)(object)label1);
			((Control)this).get_Controls().Add((Control)(object)lstRead);
			((Control)this).get_Controls().Add((Control)(object)cmdRead);
			((Control)this).get_Controls().Add((Control)(object)cmdMerge);
			((Control)this).set_Name("BAAMerge");
			((Control)this).set_Text("BAAMerge");
			((Form)this).add_Load((EventHandler)BAAMerge_Load);
			((Control)this).ResumeLayout(false);
			((Control)this).PerformLayout();
		}
	}
}
